// Code generated by go run ./scripts/generate_provider_registry; DO NOT EDIT.

package main

import (
	connector "github.com/domainry/domainry-connector-sdk"
	accounting_freee "github.com/domainry/domainry-connectors/providers/accounting/freee"
	accounting_money_forward "github.com/domainry/domainry-connectors/providers/accounting/money_forward"
	accounting_quickbooks "github.com/domainry/domainry-connectors/providers/accounting/quickbooks"
	ads_audience_meta_ads "github.com/domainry/domainry-connectors/providers/ads_audience/meta_ads"
	analytics_warehouse_bigquery "github.com/domainry/domainry-connectors/providers/analytics_warehouse/bigquery"
	analytics_warehouse_snowflake "github.com/domainry/domainry-connectors/providers/analytics_warehouse/snowflake"
	app_review_google_play_console "github.com/domainry/domainry-connectors/providers/app_review/google_play_console"
	appointment_scheduling_cal_com "github.com/domainry/domainry-connectors/providers/appointment_scheduling/cal_com"
	appointment_scheduling_calendly "github.com/domainry/domainry-connectors/providers/appointment_scheduling/calendly"
	appointment_scheduling_feishu_calendar "github.com/domainry/domainry-connectors/providers/appointment_scheduling/feishu_calendar"
	appointment_scheduling_google_calendar "github.com/domainry/domainry-connectors/providers/appointment_scheduling/google_calendar"
	appointment_scheduling_microsoft_booking "github.com/domainry/domainry-connectors/providers/appointment_scheduling/microsoft_booking"
	bank_reconciliation_plaid "github.com/domainry/domainry-connectors/providers/bank_reconciliation/plaid"
	calendar_holidays_jp "github.com/domainry/domainry-connectors/providers/calendar/holidays_jp"
	collaboration_dingtalk "github.com/domainry/domainry-connectors/providers/collaboration/dingtalk"
	collaboration_discord "github.com/domainry/domainry-connectors/providers/collaboration/discord"
	collaboration_enterprise_wechat "github.com/domainry/domainry-connectors/providers/collaboration/enterprise_wechat"
	collaboration_feishu "github.com/domainry/domainry-connectors/providers/collaboration/feishu"
	collaboration_google_workspace "github.com/domainry/domainry-connectors/providers/collaboration/google_workspace"
	collaboration_line "github.com/domainry/domainry-connectors/providers/collaboration/line"
	collaboration_line_works "github.com/domainry/domainry-connectors/providers/collaboration/line_works"
	collaboration_microsoft_365 "github.com/domainry/domainry-connectors/providers/collaboration/microsoft_365"
	collaboration_slack "github.com/domainry/domainry-connectors/providers/collaboration/slack"
	collaboration_teams "github.com/domainry/domainry-connectors/providers/collaboration/teams"
	customer_feedback_delighted "github.com/domainry/domainry-connectors/providers/customer_feedback/delighted"
	customer_feedback_surveymonkey "github.com/domainry/domainry-connectors/providers/customer_feedback/surveymonkey"
	customer_feedback_trustpilot "github.com/domainry/domainry-connectors/providers/customer_feedback/trustpilot"
	customer_feedback_typeform "github.com/domainry/domainry-connectors/providers/customer_feedback/typeform"
	delivery_operations_asana "github.com/domainry/domainry-connectors/providers/delivery_operations/asana"
	delivery_operations_jira "github.com/domainry/domainry-connectors/providers/delivery_operations/jira"
	delivery_operations_linear "github.com/domainry/domainry-connectors/providers/delivery_operations/linear"
	delivery_operations_monday "github.com/domainry/domainry-connectors/providers/delivery_operations/monday"
	delivery_operations_netsuite "github.com/domainry/domainry-connectors/providers/delivery_operations/netsuite"
	delivery_operations_odoo "github.com/domainry/domainry-connectors/providers/delivery_operations/odoo"
	delivery_operations_sap_business_one "github.com/domainry/domainry-connectors/providers/delivery_operations/sap_business_one"
	ecommerce_shopify "github.com/domainry/domainry-connectors/providers/ecommerce/shopify"
	email_smtp "github.com/domainry/domainry-connectors/providers/email/smtp"
	esign_adobe_sign "github.com/domainry/domainry-connectors/providers/esign/adobe_sign"
	esign_docusign "github.com/domainry/domainry-connectors/providers/esign/docusign"
	esign_fadada "github.com/domainry/domainry-connectors/providers/esign/fadada"
	esign_signnow "github.com/domainry/domainry-connectors/providers/esign/signnow"
	event_webinar_zoom_webinar "github.com/domainry/domainry-connectors/providers/event_webinar/zoom_webinar"
	external_database_bigquery "github.com/domainry/domainry-connectors/providers/external_database/bigquery"
	external_database_mysql "github.com/domainry/domainry-connectors/providers/external_database/mysql"
	external_database_postgres "github.com/domainry/domainry-connectors/providers/external_database/postgres"
	external_database_snowflake "github.com/domainry/domainry-connectors/providers/external_database/snowflake"
	external_database_sqlserver "github.com/domainry/domainry-connectors/providers/external_database/sqlserver"
	feishu_collaboration_feishu "github.com/domainry/domainry-connectors/providers/feishu_collaboration/feishu"
	file_storage_s3 "github.com/domainry/domainry-connectors/providers/file_storage/s3"
	help_center_confluence "github.com/domainry/domainry-connectors/providers/help_center/confluence"
	help_center_gitbook "github.com/domainry/domainry-connectors/providers/help_center/gitbook"
	help_center_help_scout_docs "github.com/domainry/domainry-connectors/providers/help_center/help_scout_docs"
	help_center_intercom_articles "github.com/domainry/domainry-connectors/providers/help_center/intercom_articles"
	help_center_notion_docs "github.com/domainry/domainry-connectors/providers/help_center/notion_docs"
	help_center_readme "github.com/domainry/domainry-connectors/providers/help_center/readme"
	help_center_zendesk_guide "github.com/domainry/domainry-connectors/providers/help_center/zendesk_guide"
	iot_telemetry_aws_iot "github.com/domainry/domainry-connectors/providers/iot_telemetry/aws_iot"
	iot_telemetry_datadog_metrics "github.com/domainry/domainry-connectors/providers/iot_telemetry/datadog_metrics"
	iot_telemetry_mqtt "github.com/domainry/domainry-connectors/providers/iot_telemetry/mqtt"
	kyc_risk_persona "github.com/domainry/domainry-connectors/providers/kyc_risk/persona"
	lead_source_tally "github.com/domainry/domainry-connectors/providers/lead_source/tally"
	lms_moodle "github.com/domainry/domainry-connectors/providers/lms/moodle"
	lms_talentlms "github.com/domainry/domainry-connectors/providers/lms/talentlms"
	logistics_authorized_carrier_gateway "github.com/domainry/domainry-connectors/providers/logistics/authorized_carrier_gateway"
	logistics_dhl "github.com/domainry/domainry-connectors/providers/logistics/dhl"
	logistics_fedex "github.com/domainry/domainry-connectors/providers/logistics/fedex"
	logistics_freightos "github.com/domainry/domainry-connectors/providers/logistics/freightos"
	logistics_sf_express "github.com/domainry/domainry-connectors/providers/logistics/sf_express"
	logistics_shopify_fulfillment "github.com/domainry/domainry-connectors/providers/logistics/shopify_fulfillment"
	logistics_ups "github.com/domainry/domainry-connectors/providers/logistics/ups"
	map_address_nominatim "github.com/domainry/domainry-connectors/providers/map_address/nominatim"
	marketplace_etsy "github.com/domainry/domainry-connectors/providers/marketplace/etsy"
	observability_compliance_prometheus "github.com/domainry/domainry-connectors/providers/observability_compliance/prometheus"
	openai_openai "github.com/domainry/domainry-connectors/providers/openai/openai"
	payment_stripe "github.com/domainry/domainry-connectors/providers/payment/stripe"
	product_event_posthog "github.com/domainry/domainry-connectors/providers/product_event/posthog"
	tariff_classification_brazil_portal_unico_classif "github.com/domainry/domainry-connectors/providers/tariff_classification/brazil_portal_unico_classif"
	tariff_classification_china_hs_bianma "github.com/domainry/domainry-connectors/providers/tariff_classification/china_hs_bianma"
	trade_statistics_comex_stat "github.com/domainry/domainry-connectors/providers/trade_statistics/comex_stat"
	weather_open_meteo "github.com/domainry/domainry-connectors/providers/weather/open_meteo"
	website_form_tally "github.com/domainry/domainry-connectors/providers/website_form/tally"
)

func providerSpecifications() []providerSpec {
	return []providerSpec{
		{importPath: "github.com/domainry/domainry-connectors/providers/accounting/freee", packageName: "freee", constructor: providerConstructor(accounting_freee.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/accounting/money_forward", packageName: "moneyforward", constructor: providerConstructor(accounting_money_forward.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/accounting/quickbooks", packageName: "quickbooks", constructor: providerConstructor(accounting_quickbooks.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/ads_audience/meta_ads", packageName: "metaads", constructor: providerConstructor(ads_audience_meta_ads.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/analytics_warehouse/bigquery", packageName: "bigquery", constructor: providerConstructor(analytics_warehouse_bigquery.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/analytics_warehouse/snowflake", packageName: "snowflake", constructor: providerConstructor(analytics_warehouse_snowflake.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/app_review/google_play_console", packageName: "googleplayconsole", constructor: providerConstructor(app_review_google_play_console.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/appointment_scheduling/cal_com", packageName: "calcom", constructor: providerConstructor(appointment_scheduling_cal_com.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/appointment_scheduling/calendly", packageName: "calendly", constructor: providerConstructor(appointment_scheduling_calendly.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/appointment_scheduling/feishu_calendar", packageName: "feishucalendar", constructor: providerConstructor(appointment_scheduling_feishu_calendar.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/appointment_scheduling/google_calendar", packageName: "googlecalendar", constructor: providerConstructor(appointment_scheduling_google_calendar.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/appointment_scheduling/microsoft_booking", packageName: "microsoftbooking", constructor: providerConstructor(appointment_scheduling_microsoft_booking.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/bank_reconciliation/plaid", packageName: "plaid", constructor: providerConstructor(bank_reconciliation_plaid.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/calendar/holidays_jp", packageName: "holidaysjp", constructor: providerConstructor(calendar_holidays_jp.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/dingtalk", packageName: "dingtalk", constructor: providerConstructor(collaboration_dingtalk.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/discord", packageName: "discord", constructor: providerConstructor(collaboration_discord.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/enterprise_wechat", packageName: "enterprisewechat", constructor: providerConstructor(collaboration_enterprise_wechat.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/feishu", packageName: "feishu", constructor: providerConstructor(collaboration_feishu.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/google_workspace", packageName: "googleworkspace", constructor: providerConstructor(collaboration_google_workspace.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/line", packageName: "line", constructor: providerConstructor(collaboration_line.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/line_works", packageName: "lineworks", constructor: providerConstructor(collaboration_line_works.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/microsoft_365", packageName: "microsoft365", constructor: providerConstructor(collaboration_microsoft_365.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/slack", packageName: "slack", constructor: providerConstructor(collaboration_slack.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/collaboration/teams", packageName: "teams", constructor: providerConstructor(collaboration_teams.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/customer_feedback/delighted", packageName: "delighted", constructor: providerConstructor(customer_feedback_delighted.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/customer_feedback/surveymonkey", packageName: "surveymonkey", constructor: providerConstructor(customer_feedback_surveymonkey.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/customer_feedback/trustpilot", packageName: "trustpilot", constructor: providerConstructor(customer_feedback_trustpilot.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/customer_feedback/typeform", packageName: "typeform", constructor: providerConstructor(customer_feedback_typeform.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/asana", packageName: "asana", constructor: providerConstructor(delivery_operations_asana.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/jira", packageName: "jira", constructor: providerConstructor(delivery_operations_jira.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/linear", packageName: "linear", constructor: providerConstructor(delivery_operations_linear.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/monday", packageName: "monday", constructor: providerConstructor(delivery_operations_monday.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/netsuite", packageName: "netsuite", constructor: providerConstructor(delivery_operations_netsuite.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/odoo", packageName: "odoo", constructor: providerConstructor(delivery_operations_odoo.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/delivery_operations/sap_business_one", packageName: "sapbusinessone", constructor: providerConstructor(delivery_operations_sap_business_one.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/ecommerce/shopify", packageName: "shopify", constructor: providerConstructor(ecommerce_shopify.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/email/smtp", packageName: "smtp", constructor: providerConstructor(email_smtp.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/esign/adobe_sign", packageName: "adobesign", constructor: providerConstructor(esign_adobe_sign.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/esign/docusign", packageName: "docusign", constructor: providerConstructor(esign_docusign.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/esign/fadada", packageName: "fadada", constructor: providerConstructor(esign_fadada.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/esign/signnow", packageName: "signnow", constructor: providerConstructor(esign_signnow.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/event_webinar/zoom_webinar", packageName: "zoomwebinar", constructor: providerConstructor(event_webinar_zoom_webinar.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/external_database/bigquery", packageName: "bigquery", constructor: providerConstructor(external_database_bigquery.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/external_database/mysql", packageName: "mysql", constructor: providerConstructor(external_database_mysql.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/external_database/postgres", packageName: "postgres", constructor: providerConstructor(external_database_postgres.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/external_database/snowflake", packageName: "snowflake", constructor: providerConstructor(external_database_snowflake.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/external_database/sqlserver", packageName: "sqlserver", constructor: providerConstructor(external_database_sqlserver.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/feishu_collaboration/feishu", packageName: "feishu", constructor: providerConstructor(feishu_collaboration_feishu.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/file_storage/s3", packageName: "s3", constructor: providerConstructor(file_storage_s3.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/confluence", packageName: "confluence", constructor: providerConstructor(help_center_confluence.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/gitbook", packageName: "gitbook", constructor: providerConstructor(help_center_gitbook.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/help_scout_docs", packageName: "helpscoutdocs", constructor: providerConstructor(help_center_help_scout_docs.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/intercom_articles", packageName: "intercomarticles", constructor: providerConstructor(help_center_intercom_articles.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/notion_docs", packageName: "notiondocs", constructor: providerConstructor(help_center_notion_docs.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/readme", packageName: "readme", constructor: providerConstructor(help_center_readme.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/help_center/zendesk_guide", packageName: "zendeskguide", constructor: providerConstructor(help_center_zendesk_guide.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/iot_telemetry/aws_iot", packageName: "awsiot", constructor: providerConstructor(iot_telemetry_aws_iot.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/iot_telemetry/datadog_metrics", packageName: "datadogmetrics", constructor: providerConstructor(iot_telemetry_datadog_metrics.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/iot_telemetry/mqtt", packageName: "mqtt", constructor: providerConstructor(iot_telemetry_mqtt.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/kyc_risk/persona", packageName: "persona", constructor: providerConstructor(kyc_risk_persona.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/lead_source/tally", packageName: "tally", constructor: providerConstructor(lead_source_tally.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/lms/moodle", packageName: "moodle", constructor: providerConstructor(lms_moodle.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/lms/talentlms", packageName: "talentlms", constructor: providerConstructor(lms_talentlms.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/authorized_carrier_gateway", packageName: "authorizedcarriergateway", constructor: providerConstructor(logistics_authorized_carrier_gateway.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/dhl", packageName: "dhl", constructor: providerConstructor(logistics_dhl.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/fedex", packageName: "fedex", constructor: providerConstructor(logistics_fedex.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/freightos", packageName: "freightos", constructor: providerConstructor(logistics_freightos.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/sf_express", packageName: "sfexpress", constructor: providerConstructor(logistics_sf_express.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/shopify_fulfillment", packageName: "shopifyfulfillment", constructor: providerConstructor(logistics_shopify_fulfillment.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/logistics/ups", packageName: "ups", constructor: providerConstructor(logistics_ups.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/map_address/nominatim", packageName: "nominatim", constructor: providerConstructor(map_address_nominatim.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/marketplace/etsy", packageName: "etsy", constructor: providerConstructor(marketplace_etsy.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/observability_compliance/prometheus", packageName: "prometheus", constructor: providerConstructor(observability_compliance_prometheus.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/openai/openai", packageName: "openai", constructor: providerConstructor(openai_openai.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/payment/stripe", packageName: "stripe", constructor: providerConstructor(payment_stripe.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/product_event/posthog", packageName: "posthog", constructor: providerConstructor(product_event_posthog.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/tariff_classification/brazil_portal_unico_classif", packageName: "brazilportalunicoclassif", constructor: providerConstructor(tariff_classification_brazil_portal_unico_classif.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/tariff_classification/china_hs_bianma", packageName: "chinahsbianma", constructor: providerConstructor(tariff_classification_china_hs_bianma.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/trade_statistics/comex_stat", packageName: "comexstat", constructor: providerConstructor(trade_statistics_comex_stat.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/weather/open_meteo", packageName: "openmeteo", constructor: providerConstructor(weather_open_meteo.New)},
		{importPath: "github.com/domainry/domainry-connectors/providers/website_form/tally", packageName: "tally", constructor: providerConstructor(website_form_tally.New)},
	}
}

func providerConstructor(constructor func(connector.Transport) (connector.Adapter, error)) func(connector.Transport) (connector.Adapter, error) {
	return constructor
}
